// Seed listings — derived from the original prototype.
// Loaded automatically the first time the database is empty.

const SEED_LISTINGS = [
  // ── Preferred sellers ──
  {
    title: 'MacBook Pro 16" M3 Max 32GB/1TB',
    price: 2400,
    category: 'electronics',
    location: 'German Village, OH',
    city: 'Columbus, OH',
    tier: 'preferred',
    seller_name: 'Avery K.',
    image_url: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=480&h=360&fit=crop&auto=format',
    description: 'Top-spec 16" MacBook Pro with the M3 Max chip, 32GB unified memory and a 1TB SSD. Barely used, AppleCare until next year. Includes original box and charger.',
  },
  {
    title: 'Leica M3 Film Camera — Mint Condition',
    price: 450,
    category: 'electronics',
    location: 'Short North, OH',
    city: 'Columbus, OH',
    tier: 'preferred',
    seller_name: 'Avery K.',
    image_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=480&h=360&fit=crop&auto=format',
    description: 'A classic Leica M3 rangefinder in mint condition. Smooth advance lever, clear viewfinder, no fungus. A true collector\u2019s piece that still shoots beautifully.',
  },
  {
    title: 'Sony WH-1000XM5 Headphones',
    price: 180,
    category: 'electronics',
    location: 'Clintonville, OH',
    city: 'Columbus, OH',
    tier: 'preferred',
    seller_name: 'Jordan M.',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=480&h=360&fit=crop&auto=format',
    description: 'Industry-leading noise cancellation, all accessories and case included. Pads are clean with no wear. Selling because I upgraded.',
  },
  {
    title: 'Minimalist Series 4 Watch — Unopened',
    price: 180,
    category: 'electronics',
    location: 'Downtown, OH',
    city: 'Columbus, OH',
    tier: 'preferred',
    seller_name: 'Jordan M.',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=480&h=360&fit=crop&auto=format',
    description: 'Brand new, factory sealed. Received as a gift and never opened. Smart enough for everyday tracking without the clutter.',
  },

  // ── Pro sellers ──
  {
    title: 'iPad Pro 12.9" M2 — 256GB + Pencil',
    price: 950,
    category: 'electronics',
    location: 'Easton, OH',
    city: 'Columbus, OH',
    tier: 'pro',
    seller_name: 'Easton Electronics',
    image_url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=480&h=360&fit=crop&auto=format',
    description: '12.9" iPad Pro with the M2 chip and 256GB storage. Comes bundled with a 2nd-gen Apple Pencil. Screen is flawless, battery health excellent.',
  },
  {
    title: 'DJI Mini 4 Pro — Under 2 Hours',
    price: 680,
    category: 'electronics',
    location: 'Worthington, OH',
    city: 'Columbus, OH',
    tier: 'pro',
    seller_name: 'SkyHigh Drones',
    image_url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=480&h=360&fit=crop&auto=format',
    description: 'Sub-250g drone with 4K HDR video and obstacle sensing. Under two hours of flight time total. Three batteries and the charging hub included.',
  },
  {
    title: 'PlayStation 5 Disc + 2 Controllers',
    price: 520,
    category: 'toys',
    location: 'Dublin, OH',
    city: 'Columbus, OH',
    tier: 'pro',
    seller_name: 'GameStash',
    image_url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=480&h=360&fit=crop&auto=format',
    description: 'Disc edition PS5 with two DualSense controllers. Cleaned, tested and reset to factory. Ready to plug in and play.',
  },
  {
    title: 'iPhone 15 Pro Max 256GB — Unlocked',
    price: 1050,
    category: 'electronics',
    location: 'Upper Arlington, OH',
    city: 'Columbus, OH',
    tier: 'pro',
    seller_name: 'Arlington Mobile',
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=480&h=360&fit=crop&auto=format',
    description: 'Factory unlocked, works on any carrier. Titanium finish, 256GB. Battery health 98%. No scratches, screen protector applied from day one.',
  },

  // ── Standard listings ──
  {
    title: 'Sonos Era 300 — Spatial Audio',
    price: 290,
    category: 'electronics',
    location: 'Victorian Village, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Casey R.',
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=480&h=360&fit=crop&auto=format',
    description: 'Room-filling spatial audio speaker with Dolby Atmos support. Works wired or over WiFi. Box and cables included.',
  },
  {
    title: 'AirPods Pro 2 — USB-C MagSafe Case',
    price: 195,
    category: 'electronics',
    location: 'Bexley, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Sam D.',
    image_url: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=480&h=360&fit=crop&auto=format',
    description: 'Latest AirPods Pro 2 with the USB-C MagSafe case. Adaptive audio and active noise cancellation. All ear tips included.',
  },
  {
    title: 'Logitech MX Keys S + MX Master 3',
    price: 85,
    category: 'electronics',
    location: 'Grandview, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Riley T.',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=480&h=360&fit=crop&auto=format',
    description: 'The classic productivity combo: MX Keys S keyboard and MX Master 3 mouse. Both pair to multiple devices. Dongles and cables included.',
  },
  {
    title: 'Samsung 65" QLED 4K — 120Hz',
    price: 740,
    category: 'electronics',
    location: 'Hilliard, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Morgan P.',
    image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=480&h=360&fit=crop&auto=format',
    description: '65" QLED 4K TV with a 120Hz panel \u2014 great for movies and gaming. Stand, remote and original box included. No dead pixels.',
  },
  {
    title: 'Nintendo Switch OLED White + 2 Games',
    price: 270,
    category: 'toys',
    location: 'Powell, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Taylor B.',
    image_url: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=480&h=360&fit=crop&auto=format',
    description: 'Switch OLED in white with a vivid 7" screen. Bundled with two physical games. Dock, joy-cons and grip all included.',
  },
  {
    title: 'GoPro Hero 12 Black + All Mounts',
    price: 310,
    category: 'electronics',
    location: 'Westerville, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Quinn L.',
    image_url: 'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=480&h=360&fit=crop&auto=format',
    description: 'Hero 12 Black with 5.3K video and HyperSmooth stabilization. Comes with the full mount kit, two batteries and a 128GB card.',
  },
  {
    title: 'Dell UltraSharp 27" 4K USB-C Monitor',
    price: 320,
    category: 'electronics',
    location: 'New Albany, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Drew H.',
    image_url: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=480&h=360&fit=crop&auto=format',
    description: '27" 4K UltraSharp panel with single-cable USB-C (charges your laptop too). Factory color calibrated. Stand adjusts every direction.',
  },
  {
    title: 'Steam Deck OLED 512GB + Dock',
    price: 490,
    category: 'toys',
    location: 'Lewis Center, OH',
    city: 'Columbus, OH',
    tier: 'standard',
    seller_name: 'Alex W.',
    image_url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=480&h=360&fit=crop&auto=format',
    description: 'OLED Steam Deck with 512GB storage plus the official dock. Carrying case included. Runs everything in my library flawlessly.',
  },
];

module.exports = { SEED_LISTINGS };
